# Creating Arrays using Numpy. 
- Each array object in Numpy is called 'ndarray', which basically stands for n-dimensions array.
- dimensions play a huge role in Numpy , so does the shape of the array and size of the array, when we perform cross-array calculations.
- We should always mention the **dtype** parameter while creating a ndarray. This parameter helps to define the data type of the underlying elements.
- If there is an array whose dtype is , let's assume int32 (32-bit signed integers), and we put an element that is out of this range, so the resultant array will overflow.
- If we perform calculations bw two arrays of same dtype, the result stays consistent, but if we perform calculations with two arrays of different dtype, then the resultant array has a new dtype, that can hold all the elements involved in this computation.

In [6]:
import numpy as np 
list = [1,2,3]
list2 = [4,5,6]
t1 = (1,2,3)

arr1 = np.array(list, dtype=np.int32)
arr2 = np.array(list2, dtype=np.int64)

arr3 = arr1 + arr2 
print(f" arr3 = {arr3}, {arr3.dtype}")
print(type(arr3))
print(arr3.shape)



 arr3 = [5 7 9], int64
<class 'numpy.ndarray'>
(3,)


# Shape/Reshape
- We can check the shape (dimensions) of an **ndarray** in numpy using .shape property.
- We can also reshape an existing ndarray using .reshape(new dimensions) property.

In [7]:
authors = ["J.K Rowling","Charles Dickens","Don quixote","Fyodor Dostoyevsky","Leo Tolstoy","Dan Brown"]
ndarr = np.array(authors, dtype = "U25")
print(ndarr)
print(ndarr.shape)

reshaped_arr = ndarr.reshape(3,2)
print(reshaped_arr.shape)
print(reshaped_arr)

['J.K Rowling' 'Charles Dickens' 'Don quixote' 'Fyodor Dostoyevsky'
 'Leo Tolstoy' 'Dan Brown']
(6,)
(3, 2)
[['J.K Rowling' 'Charles Dickens']
 ['Don quixote' 'Fyodor Dostoyevsky']
 ['Leo Tolstoy' 'Dan Brown']]


# Array Creation
- Numpy has over 40+ array creation functions, however, most of them are categorized into 3 major categories, depending on the type of array they are creating.
- 1D Array
- 2D Array 
- nD Array 

# 1D Array functions (Example)
- arange(start,stop,step) ; Creates an array from [start,end] with 'step' increment. Just like a for loop.


In [8]:
arr = np.arange(1,10,2)
print(arr)

arr2 = np.arange(5,20,5,dtype=np.int32)
print(arr2)

[1 3 5 7 9]
[ 5 10 15]


# 2D array creation functions
- np.eye(n,m) ; This function is used to create a Identity Matrix (matrix where only diagonal elements are 1, rest is 0).
```
i_mat = np.eye(3,3)
i_mat2 = np.eye(2,5)
```

- np.diag() ; This function is used to work with **Diagonal of a Matrix**.
- This function has two behaviours, changing when we give it either a 1-d array or a 2-d array.
- When we give this function a 1-d array, it creates a Square Matrix , with elements of array at diagonal, rest 0.
```
list = [1,2,3]
arr = np.diag(list)
print(arr)
[1, 0, 0
0 , 2, 0
0, 0, 3]
```

- When we give this function a 2-d array, it extracts only the diagonal elements from that matrix and returns them as a 1-d array.
```
mat = [[1,2,3],
        [4,5,6],
        [7,8,9]
        ]

output = np.diag(mat)
print(output)
[1,5,9]
```

In [9]:
list = [1,2,3]
o1 = np.diag(list)
print(o1,"\n")

mat = [[1,2,3],
        [4,5,6],
        [7,8,9]
        ]

o2 = np.diag(mat)
print(o2)

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[1 5 9]


In [10]:
# Vectorized Operations in Numpy
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ", arr1 + arr2)
print("Subtraction: ", arr2-arr1)
print("Multiplication: ", arr1 * arr2)
print("Division: ", arr1/arr2) 


Addition:  [11 22 33 44 55]
Subtraction:  [ 9 18 27 36 45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


# Element-wise Nature
- Each of the mathematical / universal operations defined in Numpy happen on a per-element basis.
- This means that if we use np.sqrt(arr) on an array, then each element's square root will be returned in the output array.
- Basically, the operation that we are using will be applied to each element in the given input ndarray.

In [11]:
# Universal Numpy Functions.
arr1 = np.array([1,2,3])
arr2 = np.array([49, 25, 9])

print("Square Root of arr2 = ", np.sqrt(arr2))
print("Exponential of arr1 = ", np.exp(arr1))

Square Root of arr2 =  [7. 5. 3.]
Exponential of arr1 =  [ 2.71828183  7.3890561  20.08553692]


In [12]:
# Slicing & Indexing Operations
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print(matrix[0][0])
print(matrix[2][1],"\n")

print(matrix[1:,2:],"\n")

# Select 1,2,5,6
print(matrix[0:2,0:2],"\n")

# Select 3, 7, 11
print(matrix[:,2],"\n")

# Select 3,4,7,8
print(matrix[:2,2:])

1
10 

[[ 7  8]
 [11 12]] 

[[1 2]
 [5 6]] 

[ 3  7 11] 

[[3 4]
 [7 8]]


In [ ]:
mat2 = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
], dtype=np.int32)

print("Shape of mat2 = ", mat2.shape)
print("dtype of mat2 = ", mat2.dtype)

print("Selecting [3,4,13,14]")
print(mat2[:2,2:4],"\n")
print("Selecting [7,8,17,18,27,28]")
print(mat2[:,6:8])

Shape of mat2 =  (3, 10)
dtype of mat2 =  int32
Selecting [3,4,13,14]
[[ 3  4]
 [13 14]] 

Selecting [7,8,15,16,25,26]
[[ 7  8]
 [17 18]
 [27 28]]


# Statistical concepts--- Normalization
- It's pretty common in ML to have mean=0 and standard_deviation=1

In [35]:
arr = np.array([1,2,3,4,5],dtype=np.int32)

mean = np.mean(arr)
deviation = np.std(arr)

normalized_arr = (arr-mean)/deviation 
print("Normalized Array = ", normalized_arr)

Normalized Array =  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
median = np.median(arr)
print("Median of array = ", median)

variance = np.var(arr)
print("Variance of array = ", variance)

Median of array =  3.0
Variance of array =  2.0


In [41]:
data = np.array([1,2,3,4,5], dtype=np.int32)

data[data<5]

print(data[data<4])

[1 2 3]
