# Creating Arrays using Numpy. 
- Each array object in Numpy is called 'ndarray', which basically stands for n-dimensions array.
- dimensions play a huge role in Numpy , so does the shape of the array and size of the array, when we perform cross-array calculations.
- We should always mention the **dtype** parameter while creating a ndarray. This parameter helps to define the data type of the underlying elements.
- If there is an array whose dtype is , let's assume int32 (32-bit signed integers), and we put an element that is out of this range, so the resultant array will overflow.
- If we perform calculations bw two arrays of same dtype, the result stays consistent, but if we perform calculations with two arrays of different dtype, then the resultant array has a new dtype, that can hold all the elements involved in this computation.

In [13]:
import numpy as np 
list = [1,2,3]
list2 = [4,5,6]
t1 = (1,2,3)

arr1 = np.array(list, dtype=np.int32)
arr2 = np.array(list2, dtype=np.int64)

arr3 = arr1 + arr2 
print(f" arr3 = {arr3}, {arr3.dtype}")
print(type(arr3))
print(arr3.shape)



 arr3 = [5 7 9], int64
<class 'numpy.ndarray'>
(3,)


# Shape/Reshape
- We can check the shape (dimensions) of an **ndarray** in numpy using .shape property.
- We can also reshape an existing ndarray using .reshape(new dimensions) property.

In [22]:
authors = ["J.K Rowling","Charles Dickens","Don quixote","Fyodor Dostoyevsky","Leo Tolstoy","Dan Brown"]
ndarr = np.array(authors, dtype = "U25")
print(ndarr)
print(ndarr.shape)

reshaped_arr = ndarr.reshape(2,3)
print(reshaped_arr.shape)
print(reshaped_arr)

['J.K Rowling' 'Charles Dickens' 'Don quixote' 'Fyodor Dostoyevsky'
 'Leo Tolstoy' 'Dan Brown']
(6,)
(2, 3)
[['J.K Rowling' 'Charles Dickens' 'Don quixote']
 ['Fyodor Dostoyevsky' 'Leo Tolstoy' 'Dan Brown']]


# Array Creation
- Numpy has over 40+ array creation functions, however, most of them are categorized into 3 major categories, depending on the type of array they are creating.
- 1D Array
- 2D Array 
- nD Array 

# 1D Array functions (Example)
- arange(start,stop,step) ; Creates an array from [start,end] with 'step' increment. Just like a for loop.


In [26]:
arr = np.arange(1,10,2)
print(arr)

arr2 = np.arange(5,20,5,dtype=np.int32)
print(arr2)

[1 3 5 7 9]
[ 5 10 15]


# 2D array creation functions
- np.eye(n,m) ; This function is used to create a Identity Matrix (matrix where only diagonal elements are 1, rest is 0).
```
i_mat = np.eye(3,3)
i_mat2 = np.eye(2,5)
```

- np.diag() ; This function is used to work with **Diagonal of a Matrix**.
- This function has two behaviours, changing when we give it either a 1-d array or a 2-d array.
- When we give this function a 1-d array, it creates a Square Matrix , with elements of array at diagonal, rest 0.
```
list = [1,2,3]
arr = np.diag(list)
print(arr)
[1, 0, 0
0 , 2, 0
0, 0, 3]
```

- When we give this function a 2-d array, it extracts only the diagonal elements from that matrix and returns them as a 1-d array.
```
mat = [[1,2,3],
        [4,5,6],
        [7,8,9]
        ]

output = np.diag(mat)
print(output)
[1,5,9]
```

In [28]:
list = [1,2,3]
o1 = np.diag(list)
print(o1,"\n")

mat = [[1,2,3],
        [4,5,6],
        [7,8,9]
        ]

o2 = np.diag(mat)
print(o2)

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[1 5 9]
